In [3]:
#importing the libraries
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

In [2]:
#Upload data file from local drive to google colab
from google.colab import files
uploaded = files.upload()

Saving iris.data to iris.data


In [3]:
#ID no: 18IT033
#Assigning column names for the dataset
headernames = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'Class']
#importing dataset
dataset = pd.read_csv('iris.data', names = headernames)
dataset.head()

sepal-length  sepal-width  petal-length  petal-width        Class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [6]:
#Total observations in the dataset
print("Count of samples in each class before encoding:\n",dataset['Class'].value_counts())
print("Classes:\n",dataset['Class'])
print(dataset.shape)
print(dataset.count())

Count of samples in each class before encoding:
 Iris-setosa        50
Iris-virginica     50
Iris-versicolor    50
Name: Class, dtype: int64
Classes:
 0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...      
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: Class, Length: 150, dtype: object
(150, 5)
sepal-length    150
sepal-width     150
petal-length    150
petal-width     150
Class           150
dtype: int64


# **Encoding**

In [15]:
# Importing LabelEncoder and initializing it
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
dataset['Class']=le.fit_transform(dataset['Class'])
print("Count of samples in each class after encoding:\n",dataset['Class'].value_counts())
print("Classes: ",le.classes_)
dataset

Count of samples in each class after encoding:
 2    50
1    50
0    50
Name: Class, dtype: int64
Classes:  [0 1 2]


sepal-length  sepal-width  petal-length  petal-width  Class
0             5.1          3.5           1.4          0.2      0
1             4.9          3.0           1.4          0.2      0
2             4.7          3.2           1.3          0.2      0
3             4.6          3.1           1.5          0.2      0
4             5.0          3.6           1.4          0.2      0
..            ...          ...           ...          ...    ...
145           6.7          3.0           5.2          2.3      2
146           6.3          2.5           5.0          1.9      2
147           6.5          3.0           5.2          2.0      2
148           6.2          3.4           5.4          2.3      2
149           5.9          3.0           5.1          1.8      2

[150 rows x 5 columns]

In [14]:
#Performing one hot encoding
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder()
encoded_data = encoder.fit_transform(dataset['Class'].values.reshape(-1,1)).toarray()
print("Encoded Categories: ",encoder.categories_)


#Transforming the encoded data to dataframe
encoded_data = pd.DataFrame(encoded_data , columns = ['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'])
encoded_data

Encoded Categories:  [array([0, 1, 2])]


Iris-setosa  Iris-versicolor  Iris-virginica
0            1.0              0.0             0.0
1            1.0              0.0             0.0
2            1.0              0.0             0.0
3            1.0              0.0             0.0
4            1.0              0.0             0.0
..           ...              ...             ...
145          0.0              0.0             1.0
146          0.0              0.0             1.0
147          0.0              0.0             1.0
148          0.0              0.0             1.0
149          0.0              0.0             1.0

[150 rows x 3 columns]

# **Standardization**

In [19]:
#Standardization
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
X = dataset.drop(['Class'], axis = 'columns')
y = dataset.Class
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2)

#Performing scaling using StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
print("Scaled train data: ", X_train)

Scaled train data:  [[-1.47890835  0.7916453  -1.31848371 -1.16313522]
 [-1.71792384  0.34459854 -1.37519268 -1.29593848]
 [-0.16432315 -0.54949498  0.21265866  0.16489738]
 [-1.47890835  0.12107516 -1.26177473 -1.29593848]
 [-0.16432315 -0.10244822  0.26936764  0.03209412]
 [ 1.38927754  0.34459854  0.55291252  0.29770064]
 [ 0.31370783 -0.54949498  0.55291252  0.03209412]
 [ 2.10632402 -0.10244822  1.63038308  1.22732346]
 [-0.76186188  0.7916453  -1.31848371 -1.29593848]
 [ 1.03075431 -1.22006512  1.17671126  0.82891368]
 [ 0.07469234  0.34459854  0.6096215   0.82891368]
 [ 1.15026205 -0.54949498  0.6096215   0.29770064]
 [-0.52284639  0.7916453  -1.26177473 -1.03033196]
 [ 2.22583176  1.68573882  1.68709205  1.36012672]
 [ 2.22583176 -0.99654174  1.80051001  1.49292998]
 [ 1.03075431 -0.10244822  0.72303945  0.69611042]
 [-0.88136962  1.01516868 -1.31848371 -1.16313522]
 [ 0.67223107  0.34459854  0.43949457  0.4305039 ]
 [ 0.67223107 -0.54949498  1.06329331  1.36012672]
 [-1.239892

# **Normalization**

In [21]:
#Normalization
from sklearn.preprocessing import normalize
X = dataset.drop(['Class'], axis = 'columns')
X_normalized = normalize(X, norm='l2')
print("Normalized Data:\n",X_normalized)

Normalized Data:
 [[0.80377277 0.55160877 0.22064351 0.0315205 ]
 [0.82813287 0.50702013 0.23660939 0.03380134]
 [0.80533308 0.54831188 0.2227517  0.03426949]
 [0.80003025 0.53915082 0.26087943 0.03478392]
 [0.790965   0.5694948  0.2214702  0.0316386 ]
 [0.78417499 0.5663486  0.2468699  0.05808704]
 [0.78010936 0.57660257 0.23742459 0.0508767 ]
 [0.80218492 0.54548574 0.24065548 0.0320874 ]
 [0.80642366 0.5315065  0.25658935 0.03665562]
 [0.81803119 0.51752994 0.25041771 0.01669451]
 [0.80373519 0.55070744 0.22325977 0.02976797]
 [0.786991   0.55745196 0.26233033 0.03279129]
 [0.82307218 0.51442011 0.24006272 0.01714734]
 [0.8025126  0.55989251 0.20529392 0.01866308]
 [0.81120865 0.55945424 0.16783627 0.02797271]
 [0.77381111 0.59732787 0.2036345  0.05430253]
 [0.79428944 0.57365349 0.19121783 0.05883625]
 [0.80327412 0.55126656 0.22050662 0.04725142]
 [0.8068282  0.53788547 0.24063297 0.04246464]
 [0.77964883 0.58091482 0.22930848 0.0458617 ]
 [0.8173379  0.51462016 0.25731008 0.03027

# **Discretization**

In [22]:
#Discretization
from sklearn.preprocessing import KBinsDiscretizer
kbins = KBinsDiscretizer(n_bins=10, encode='ordinal', strategy='uniform')
X = dataset.drop(['Class'], axis = 'columns')
data_trans = kbins.fit_transform(X)
print("Data after performing discretization:\n",data_trans)

Data after performing discretization:
 [[2. 6. 0. 0.]
 [1. 4. 0. 0.]
 [1. 5. 0. 0.]
 [0. 4. 0. 0.]
 [1. 6. 0. 0.]
 [3. 7. 1. 1.]
 [0. 5. 0. 0.]
 [1. 5. 0. 0.]
 [0. 3. 0. 0.]
 [1. 4. 0. 0.]
 [3. 7. 0. 0.]
 [1. 5. 1. 0.]
 [1. 4. 0. 0.]
 [0. 4. 0. 0.]
 [4. 8. 0. 0.]
 [3. 9. 0. 1.]
 [3. 7. 0. 1.]
 [2. 6. 0. 0.]
 [3. 7. 1. 0.]
 [2. 7. 0. 0.]
 [3. 5. 1. 0.]
 [2. 7. 0. 1.]
 [0. 6. 0. 0.]
 [2. 5. 1. 1.]
 [1. 5. 1. 0.]
 [1. 4. 1. 0.]
 [1. 5. 1. 1.]
 [2. 6. 0. 0.]
 [2. 5. 0. 0.]
 [1. 5. 1. 0.]
 [1. 4. 1. 0.]
 [3. 5. 0. 1.]
 [2. 8. 0. 0.]
 [3. 9. 0. 0.]
 [1. 4. 0. 0.]
 [1. 5. 0. 0.]
 [3. 6. 0. 0.]
 [1. 4. 0. 0.]
 [0. 4. 0. 0.]
 [2. 5. 0. 0.]
 [1. 6. 0. 0.]
 [0. 1. 0. 0.]
 [0. 5. 0. 0.]
 [1. 6. 1. 2.]
 [2. 7. 1. 1.]
 [1. 4. 0. 0.]
 [2. 7. 1. 0.]
 [0. 5. 0. 0.]
 [2. 7. 0. 0.]
 [1. 5. 0. 0.]
 [7. 5. 6. 5.]
 [5. 5. 5. 5.]
 [7. 4. 6. 5.]
 [3. 1. 5. 5.]
 [6. 3. 6. 5.]
 [3. 3. 5. 5.]
 [5. 5. 6. 6.]
 [1. 1. 3. 3.]
 [6. 3. 6. 5.]
 [2. 2. 4. 5.]
 [1. 0. 4. 3.]
 [4. 4. 5. 5.]
 [4. 0. 5. 3.]
 [5. 3. 6. 5.]
 

# **Imputation of missing values**

In [13]:
#Imputation of missing values
#Upload data file from local drive to google colab
from google.colab import files
uploaded = files.upload()

Saving impute_iris.csv to impute_iris (2).csv


In [17]:
#Assigning column names for the dataset
headernames = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'Class']
#importing dataset
df = pd.read_csv('impute_iris (2).csv', names = headernames)
df

sepal-length  sepal-width  petal-length  petal-width           Class
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          NaN           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [16]:
#Checking null values in dataset
df.isnull().sum()

sepal-length    0
sepal-width     2
petal-length    0
petal-width     1
Class           0
dtype: int64

In [20]:
from sklearn.impute import SimpleImputer

X = df.drop(['Class'], axis = 'columns')
my_imputer = SimpleImputer()
imputed_data = my_imputer.fit_transform(X)
print("Imputed data:\n",imputed_data)

Imputed data:
 [[5.1        3.5        1.4        0.2       ]
 [4.9        3.         1.4        0.2       ]
 [4.7        3.2        1.3        0.2       ]
 [4.6        3.1        1.5        0.2       ]
 [5.         3.6        1.4        0.2       ]
 [5.4        3.9        1.7        0.4       ]
 [4.6        3.4        1.4        0.3       ]
 [5.         3.4        1.5        0.2       ]
 [4.4        2.9        1.4        0.2       ]
 [4.9        3.1        1.5        0.1       ]
 [5.4        3.7        1.5        0.2       ]
 [4.8        3.4        1.6        0.2       ]
 [4.8        3.         1.4        0.1       ]
 [4.3        3.         1.1        0.1       ]
 [5.8        4.         1.2        0.2       ]
 [5.7        4.4        1.5        0.4       ]
 [5.4        3.9        1.3        0.4       ]
 [5.1        3.5        1.4        0.3       ]
 [5.7        3.8        1.7        0.3       ]
 [5.1        3.8        1.5        0.3       ]
 [5.4        3.4        1.7        0.2       

In [22]:
#Checking if any null values after imputation of missing values
pd.DataFrame(imputed_data).isnull().sum()

0    0
1    0
2    0
3    0
dtype: int64